### ISSUE TITLE
Build with stable Rust

### ISSUE THREAD

**Issue by pka** [jeremiah-shaulov/nop-json#2]
I'm looking for a streaming JSON parser and nop-json looks very promising for my use case!

Compiling with stable I get
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/nop-json-1.0.9/src/lib.rs:1:1
  |
1 | #![feature(specialization)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Doesn't look like this will be [stabilized soon](https://github.com/rust-lang/rust/issues/31844#issuecomment-786080490). Is this required, or is there a chance to get nop-json built with stable Rust?

**Comment by jeremiah-shaulov** [comment]
Hi. nop-json 1.1 uses specialization to distinguish types that implement `Default`, so such fields in struct can be optional, from other types. According to the discussion you mentioned i understand that i need to get rid of this feature. The solution can be to require all fields to implement `Default`. I'll think what i can do.

**Comment by jeremiah-shaulov** [comment]
Hi. I issued nop-json v2.0.1. Tell me what do you think about it.
